//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsBuildConvertToProjectReference.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsBuildConvertToProjectReference.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsBuildConvertToProjectReference
        ///Scans given directory for MSBuild Style Projects and Converts their References
        ///to ProjectReferences if the Project was found in the Lookup Directories.
        ///
        ///Invalid Command/Arguments. Valid commands are:
        ///
        ///MsBuildConvertToProjectReference [targetDirectory] [lookupDirectory]+
        ///    [MODIFIES] Spins through targetDirectory and all subdirectories for
        ///    MSBuild Project Format Files and attempts to convert any Reference Elements
        ///    to ProjectReference if the Project can be f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpTextMessage {
            get {
                return ResourceManager.GetString("HelpTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided directory `{0}` is invalid..
        /// </summary>
        internal static string InvalidDirectoryArgument {
            get {
                return ResourceManager.GetString("InvalidDirectoryArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a directory to scan as well as the lookup directories..
        /// </summary>
        internal static string NotEnoughDirectoryArguments {
            get {
                return ResourceManager.GetString("NotEnoughDirectoryArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the directories specified was invalid (see above)..
        /// </summary>
        internal static string OneOrMoreInvalidDirectories {
            get {
                return ResourceManager.GetString("OneOrMoreInvalidDirectories", resourceCulture);
            }
        }
    }
}
